In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

print("Setup Successful 🚀")

Setup Successful 🚀

In [17]:
# Load dataset
df = pd.read_csv("food_delivery.csv")

# Show first 5 rows
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [18]:
# Remove '(min) ' from target column
df['Time_taken(min)'] = df['Time_taken(min)'].str.replace('(min) ', '')

# Convert to integer
df['Time_taken(min)'] = df['Time_taken(min)'].astype(int)

# Check result
df['Time_taken(min)'].head()

0    24
1    33
2    26
3    21
4    30
Name: Time_taken(min), dtype: int64

In [19]:
# Drop unnecessary columns
df = df.drop(['ID', 'Delivery_person_ID'], axis=1)

# Check remaining columns
df.columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='str')

In [20]:
# Check missing values
df.isnull().sum()

Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [21]:
df.select_dtypes(include='object').columns

C:\Users\yasha\AppData\Local\Temp\ipykernel_14976\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Order_Date',
       'Time_Orderd', 'Time_Order_picked', 'Weatherconditions',
       'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='str')

In [23]:
# Convert to numeric
df['Delivery_person_Age'] = pd.to_numeric(df['Delivery_person_Age'], errors='coerce')
df['Delivery_person_Ratings'] = pd.to_numeric(df['Delivery_person_Ratings'], errors='coerce')
df['multiple_deliveries'] = pd.to_numeric(df['multiple_deliveries'], errors='coerce')

df.select_dtypes(include='object').columns

C:\Users\yasha\AppData\Local\Temp\ipykernel_14976\3168834940.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Order_Date', 'Time_Orderd', 'Time_Order_picked', 'Weatherconditions',
       'Road_traffic_density', 'Type_of_order', 'Type_of_vehicle', 'Festival',
       'City'],
      dtype='str')

In [24]:
df = df.drop(['Order_Date', 'Time_Orderd', 'Time_Order_picked'], axis=1)

# Check remaining categorical columns again
df.select_dtypes(include='object').columns

C:\Users\yasha\AppData\Local\Temp\ipykernel_14976\1378386463.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Weatherconditions', 'Road_traffic_density', 'Type_of_order',
       'Type_of_vehicle', 'Festival', 'City'],
      dtype='str')

In [25]:
df = pd.get_dummies(df, drop_first=True)

# Check result
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken(min),Weatherconditions_conditions Fog,...,Type_of_order_Meal,Type_of_order_Snack,Type_of_vehicle_electric_scooter,Type_of_vehicle_motorcycle,Type_of_vehicle_scooter,Festival_No,Festival_Yes,City_NaN,City_Semi-Urban,City_Urban
0,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2,0.0,24,False,...,False,True,False,True,False,True,False,False,False,True
1,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2,1.0,33,False,...,False,True,False,False,True,True,False,False,False,False
2,23.0,4.4,12.914264,77.678400,12.924264,77.688400,0,1.0,26,False,...,False,False,False,True,False,True,False,False,False,True
3,38.0,4.7,11.003669,76.976494,11.053669,77.026494,0,1.0,21,False,...,False,False,False,True,False,True,False,False,False,False
4,32.0,4.6,12.972793,80.249982,13.012793,80.289982,1,1.0,30,False,...,False,True,False,False,True,True,False,False,False,False

In [26]:
# Define X (features) and y (target)
X = df.drop('Time_taken(min)', axis=1)
y = df['Time_taken(min)']

# Check shapes
X.shape, y.shape

((45593, 29), (45593,))

In [27]:
from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Check shapes
X_train.shape, X_test.shape

((36474, 29), (9119, 29))

In [28]:
from sklearn.linear_model import LinearRegression

# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [29]:
# Check missing values again
df.isnull().sum()

Delivery_person_Age                        1854
Delivery_person_Ratings                    1908
Restaurant_latitude                           0
Restaurant_longitude                          0
Delivery_location_latitude                    0
Delivery_location_longitude                   0
Vehicle_condition                             0
multiple_deliveries                         993
Time_taken(min)                               0
Weatherconditions_conditions Fog              0
Weatherconditions_conditions NaN              0
Weatherconditions_conditions Sandstorms       0
Weatherconditions_conditions Stormy           0
Weatherconditions_conditions Sunny            0
Weatherconditions_conditions Windy            0
Road_traffic_density_Jam                      0
Road_traffic_density_Low                      0
Road_traffic_density_Medium                   0
Road_traffic_density_NaN                      0
Type_of_order_Drinks                          0
Type_of_order_Meal                            0
Type_of_order_Snack                           0
Type_of_vehicle_electric_scooter              0
Type_of_vehicle_motorcycle                    0
Type_of_vehicle_scooter                       0
Festival_No                                   0
Festival_Yes                                  0
City_NaN                                      0
City_Semi-Urban                               0
City_Urban                                    0
dtype: int64

In [33]:
# Fill missing values with mean
df['Delivery_person_Age'] = df['Delivery_person_Age'].fillna(df['Delivery_person_Age'].mean())
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].fillna(df['Delivery_person_Ratings'].mean())
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(df['multiple_deliveries'].mean())

In [34]:
# Rechecking missing values after handelingdf.isnull().sum()
df.isnull().sum()

Delivery_person_Age                        0
Delivery_person_Ratings                    0
Restaurant_latitude                        0
Restaurant_longitude                       0
Delivery_location_latitude                 0
Delivery_location_longitude                0
Vehicle_condition                          0
multiple_deliveries                        0
Time_taken(min)                            0
Weatherconditions_conditions Fog           0
Weatherconditions_conditions NaN           0
Weatherconditions_conditions Sandstorms    0
Weatherconditions_conditions Stormy        0
Weatherconditions_conditions Sunny         0
Weatherconditions_conditions Windy         0
Road_traffic_density_Jam                   0
Road_traffic_density_Low                   0
Road_traffic_density_Medium                0
Road_traffic_density_NaN                   0
Type_of_order_Drinks                       0
Type_of_order_Meal                         0
Type_of_order_Snack                        0
Type_of_vehicle_electric_scooter           0
Type_of_vehicle_motorcycle                 0
Type_of_vehicle_scooter                    0
Festival_No                                0
Festival_Yes                               0
City_NaN                                   0
City_Semi-Urban                            0
City_Urban                                 0
dtype: int64

In [35]:
# Define X and y
X = df.drop('Time_taken(min)', axis=1)
y = df['Time_taken(min)']

# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [38]:
model

LinearRegression()

In [36]:
model.coef_

array([ 3.84890948e-01, -7.20067789e+00,  5.75454020e-03, -2.40429397e-03,
        6.04440900e-03,  8.53632623e-04, -2.09548942e+00,  3.20499941e+00,
        7.32616077e-02, -9.39680707e-01, -2.69054484e+00, -2.72133680e+00,
       -6.02990669e+00, -2.56980053e+00,  2.84861842e+00, -5.25164182e+00,
       -2.96303208e-01, -6.02657442e-02, -1.13294938e-01,  5.58587659e-02,
        3.85865566e-02,  5.63411987e-01,  2.12973201e-01, -2.87098098e-01,
        7.30393472e+00,  1.76579140e+01, -2.70949430e+00,  1.02950503e+01,
       -2.14176357e+00])

In [39]:
model.intercept_

np.float64(44.15667469680709)

In [40]:
print("Model trained successfully 🚀")

Model trained successfully 🚀

In [41]:
# Make predictions
y_pred = model.predict(X_test)

# Show first 5 predictions
y_pred[:5]

array([37.53767415, 34.92718814, 34.55666426, 35.4441261 , 31.68319617])

In [42]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

MAE: 4.888955638264991
MSE: 38.36402725500152
R2 Score: 0.5624447703118162

In [43]:
import pickle

# Save model
pickle.dump(model, open("model.pkl", "wb"))

In [44]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Vehicle_condition,multiple_deliveries,Time_taken(min),Weatherconditions_conditions Fog,...,Type_of_order_Meal,Type_of_order_Snack,Type_of_vehicle_electric_scooter,Type_of_vehicle_motorcycle,Type_of_vehicle_scooter,Festival_No,Festival_Yes,City_NaN,City_Semi-Urban,City_Urban
0,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2,0.0,24,False,...,False,True,False,True,False,True,False,False,False,True
1,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2,1.0,33,False,...,False,True,False,False,True,True,False,False,False,False
2,23.0,4.4,12.914264,77.678400,12.924264,77.688400,0,1.0,26,False,...,False,False,False,True,False,True,False,False,False,True
3,38.0,4.7,11.003669,76.976494,11.053669,77.026494,0,1.0,21,False,...,False,False,False,True,False,True,False,False,False,False
4,32.0,4.6,12.972793,80.249982,13.012793,80.289982,1,1.0,30,False,...,False,True,False,False,True,True,False,False,False,False

In [45]:
list(X.columns)

['Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Vehicle_condition',
 'multiple_deliveries',
 'Weatherconditions_conditions Fog',
 'Weatherconditions_conditions NaN',
 'Weatherconditions_conditions Sandstorms',
 'Weatherconditions_conditions Stormy',
 'Weatherconditions_conditions Sunny',
 'Weatherconditions_conditions Windy',
 'Road_traffic_density_Jam ',
 'Road_traffic_density_Low ',
 'Road_traffic_density_Medium ',
 'Road_traffic_density_NaN ',
 'Type_of_order_Drinks ',
 'Type_of_order_Meal ',
 'Type_of_order_Snack ',
 'Type_of_vehicle_electric_scooter ',
 'Type_of_vehicle_motorcycle ',
 'Type_of_vehicle_scooter ',
 'Festival_No ',
 'Festival_Yes ',
 'City_NaN ',
 'City_Semi-Urban ',
 'City_Urban ']